version: '3.4'

services:
  hugo:
    build:
      context: .
      target: builder
    container_name: hugo
    ports:
     - "1313:1313"
    volumes:
     - ./site:/usr/share/site
    command: hugo serve --bind=0.0.0.0 --disableFastRender

