version: '3.4'

services:
  hugo:
    build:
      context: .
      target: prod
    container_name: hugo_nginx
    networks:
     - web
    labels:
      - "traefik.enable=true"
      - "traefik.backend=hugo_nginx"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:glukoo.si"
      - "traefik.port=80"
    restart: always

networks:
  web:
    external: true
